### ISSUE TITLE
practica3_web3.0_Abigail Coronel Santiago

### ISSUE THREAD

**Issue by abicoronel** [SistemasTecTlaxiaco/actividad-6-practica-de-proceso-de-negocio-con-web-30-equipo_judith#1]
[practica 3 web 3,0.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-proceso-de-negocio-con-web-30-equipo_judith/files/9650115/practica.3.web.3.0.pdf)

**Comment by EdwinOrtiz1412** [comment]
calificación: 20 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
